services:
  - type: web
    name: approval-service
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/approval-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: true
